---

- name: Configure glance API
  ini_file: dest=/etc/glance/glance-api.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  database
      option:   connection
      value:    "mysql://glance:{{ glance_dbpass }}@{{ mysql_hostname }}/glance"
    - section:  DEFAULT
      option:   rpc_backend
      value:    rabbit
    - section:  DEFAULT
      option:   rabbit_host
      value:    "{{ rabbit_hostname }}"
    - section:  DEFAULT
      option:   rabbit_userid
      value:    "{{ rabbit_username }}"
    - section:  DEFAULT
      option:   rabbit_password
      value:    "{{ rabbit_pass }}"
    - section:  keystone_authtoken
      option:   auth_uri
      value:    "http://{{ keystone_hostname }}:{{ keystone_port }}/v2.0"
    - section:  keystone_authtoken
      option:   auth_host
      value:    "{{ keystone_hostname }}"
    - section:  keystone_authtoken
      option:   auth_port
      value:    "{{ keystone_admin_port }}"
    - section:  keystone_authtoken
      option:   auth_protocol
      value:    http
    - section:  keystone_authtoken
      option:   admin_tenant_name
      value:    service
    - section:  keystone_authtoken
      option:   admin_user
      value:    glance
    - section:  keystone_authtoken
      option:   admin_password
      value:    "{{ glance_pass }}"
    - section:  paste_deploy
      option:   flavor
      value:    keystone
  notify:
    - Restart glance API

- name: Configure glance registry
  ini_file: dest=/etc/glance/glance-registry.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  database
      option:   connection
      value:    "mysql://glance:{{ glance_dbpass }}@{{ mysql_hostname }}/glance"
    - section:  keystone_authtoken
      option:   auth_uri
      value:    "http://{{ keystone_hostname }}:{{ keystone_port }}/v2.0"
    - section:  keystone_authtoken
      option:   auth_host
      value:    "{{ keystone_hostname }}"
    - section:  keystone_authtoken
      option:   auth_port
      value:    "{{ keystone_admin_port }}"
    - section:  keystone_authtoken
      option:   auth_protocol
      value:    http
    - section:  keystone_authtoken
      option:   admin_tenant_name
      value:    service
    - section:  keystone_authtoken
      option:   admin_user
      value:    glance
    - section:  keystone_authtoken
      option:   admin_password
      value:    "{{ glance_pass }}"
    - section:  paste_deploy
      option:   flavor
      value:    keystone
  notify:
    - Restart glance registry
