---

- name: "Dump service list"
  shell: keystone service-list
  register: service_list
  changed_when: false
  environment: openstack_service_env

- name: "Dump endpoint list"
  shell: keystone endpoint-list
  register: endpoint_list
  changed_when: false
  environment: openstack_service_env

- name: Create the service entity for the image service
  shell: keystone service-create --name glance --type image --description="OpenStack Image Service"
  environment: openstack_service_env
  when: "service_list.stdout.find('glance') == -1"

- name: "Dump image service id"
  shell: keystone service-list | awk '/ image / {print $2}'
  register: image_service_id
  changed_when: false
  environment: openstack_service_env

- name: Create the API endpoint for the image service
  shell: >
    keystone endpoint-create \
      --service-id={{ image_service_id.stdout }} \
      --publicurl=http://{{ glance_hostname }}:{{ glance_port }} \
      --internalurl=http://{{ glance_hostname }}:{{ glance_port }} \
      --adminurl=http://{{ glance_hostname }}:{{ glance_port }}
  when: "endpoint_list.stdout.find('{{ image_service_id.stdout }}') == -1"
  environment: openstack_service_env
