---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Set service facts
  set_fact:
    openstack_glance_api_service: 'glance-api'
    openstack_glance_registry_service: 'glance-registry'
    openstack_glance_database_migration_repository: >-
      /usr/lib/python2.7/dist-packages/glance/db/sqlalchemy/migrate_repo/versions
  when: ansible_os_family == 'Debian'

- name: Set service facts
  set_fact:
    openstack_glance_api_service: 'openstack-glance-api'
    openstack_glance_registry_service: 'openstack-glance-registry'
    openstack_glance_database_migration_repository: >-
      /usr/lib/python2.7/site-packages/glance/db/sqlalchemy/migrate_repo/versions
  when: ansible_os_family == 'RedHat'
