---

- name: SANITY CHECK List glance images
  shell: >-
    openstack
    --os-identity-api-version 3
    --os-auth-url {{ openstack_glance_keystone_protocol }}://{{ openstack_glance_keystone_hostname }}:{{ openstack_glance_keystone_port }}/v3
    --os-project-name '{{ openstack_glance_demo_project }}'
    --os-username '{{ openstack_glance_demo_user }}'
    --os-auth-type password
    --os-password '{{ openstack_glance_demo_pass }}'
    --os-user-domain-id default
    --os-project-domain-id default
    image list
  register: image_list_test
  changed_when: image_list_test.rc != 0

- debug: var=image_list_test.stdout_lines
