---

- name: SANITY CHECK List glance images
  shell: >-
    openstack
    --os-auth-url {{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_port }}/v2.0
    --os-project-name '{{ demo_project }}'
    --os-username '{{ demo_user }}'
    --os-auth-type password
    --os-password '{{ demo_pass }}'
    image list
  register: image_list_test
  changed_when: image_list_test.rc != 0

- debug: var=image_list_test.stdout_lines
